### PR TITLE
Upgrade es2015 build

### PR DESCRIPTION
**Pull request by TrySound**
You don't need afraid minors if you use normal packages which follows semver.
Why do you need source maps?

### CODE REVIEW

**Comment by tinchoz49** [comment]
Sometimes i use iron-node to analize the execution and is better with a source map.

**Comment by TrySound** [comment]
@tinchoz49 Do you want to return iron-node and fix path?

**Comment by tinchoz49** [comment]
no, it's ok. But please don't remove the watch (start) task.

**Comment by TrySound** [comment]
@tinchoz49 Why you need it? Test does not require watching.

**Comment by tinchoz49** [comment]
yes, you right that is something i made to use with the iron-node.

**Comment by TrySound** [comment]
@tinchoz49 Can you upgrade your eslint-config? Need at least add all peer stuff in redular dependencies.

**Comment by TrySound** [comment]
Do you need in this source map node_modules?

**Comment by tinchoz49** [comment]
no, why do i need that?

**Comment by TrySound** [comment]
@tinchoz49 I mean in this case maybe better remove sourcemap option in build script

**Pull request merged**
