### PR TITLE
Use ava

### PR DESCRIPTION
**Pull request by TrySound**
I'd like to split common-tests, but in the next pr.

### CODE REVIEW

**Comment by TrySound** [comment]
Can you give me access?

**Comment by TrySound** [comment]
Is everything okay here?

**Comment by tinchoz49** [comment]
yes, i agree with the rewrite that you are doing

**Comment by TrySound** [comment]
Merge?

**Comment by tinchoz49** [comment]
I give you `write` access, I thought you could do merge.

**Comment by TrySound** [comment]
Oh, I just wanted it for simple branches handling. Usually owners accept my pull requests.

**Comment by tinchoz49** [comment]
ahh ok :+1:

**Pull request merged**
