### PR TITLE
Add copy module

### PR DESCRIPTION
**Pull request by TrySound**
I made pretty module with caching copying. But I don't have idea (yet) how to integrate it. The problem is hashFunction which should get contents to generate template. I tried make splitted modules, but single module is the best way for this.

### CODE REVIEW

**Comment by TrySound** [comment]
Okay. I did it.  I guess. It's 5 a.m. I'm not absolutly sure in this pr. Need some fresh head.

**Comment by TrySound** [comment]
Okay. I'll split a bit.

**Comment by tinchoz49** [comment]
i think we are good to merge and maybe release a minor version.

**Comment by TrySound** [comment]
Wait! I'll have some better refactoring. :)

**Pull request merged**
