### PR TITLE
Test refactor

### PR DESCRIPTION
**Pull request by TrySound**
Hey! Just thought about test presentation. Did you think about changing test lib? Tape is very bad decision for promise based libs. Substack don't like promises. That sucks. Now we use [ava](https://github.com/sindresorhus/ava) (in postcss boilerplate too). It's really great. The main idea is more atomic tests. Output becomes more readable and debugging simpler. Can I rewrite tests with it?

### CODE REVIEW

**Comment by tinchoz49** [comment]
wow!! yes absolutely! ava is great!!

**Comment by TrySound** [comment]
Will do it tomorrow. Leave some comments for my commit if something is not okay.

**Comment by tinchoz49** [comment]
ok! thanks for your work!

**Comment by tinchoz49** [comment]
these changes are ok! i'm going to merge it. Please, create another pull request for the AVA rewrite tests or if you want i can rewrite it and follow a structure similar to your tests in postcss-inline-svg.

**Pull request merged**
